name: chatty
channels:
- defaults
- conda-forge
dependencies:
- pip
- jupyter
- nltk
- numpy
- pandas
- scipy
- requests
- pip:
  - pyyaml
  - emoji
  - vaderSentiment
  - tabulate
  - wordcloud
  - grapheme
  - pytz
